# The main entry point of your workflow.
rule bwa_map:
    input:
        "resources/Rothia_mucilaginosa_43675.AP014938.1.fasta",
        "/var/lib/ont/SISPA2/barcode03/Rothia_mucilaginosa.fastq"
    output:
        "results/A.bam"
    shell:
        "bwa mem {input} | samtools view -Sb - > {output}"


#report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
#singularity: "docker://continuumio/miniconda3"


#rule all:
#    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.


#include: "rules/common.smk"
#include: "rules/other.smk"
